Next → Horus
elementary/os-patches pull request #248
Opened 2022-05-25 23:59 UTC by danrabbit

2022-05-26 00:09 UTC, ZenitsuDev submitted a review, later dismissed

2022-05-29 19:33 UTC, tintou submitted a review, later dismissed

2022-10-03 19:26 UTC, tintou commented
@danirabbit can you resolve the conflicts here?

2022-10-04 06:35 UTC, tintou requested changes

2022-10-04 15:35 UTC, merged